package com.android.unio.model.strings.test_tags.event

object EventCardTestTags {
  const val EVENT_ITEM = "event_EventListItem"
  const val EVENT_IMAGE = "event_EventImage"
  const val EVENT_TITLE = "event_EventTitle"
  const val EVENT_MAIN_TYPE = "event_EventMainType"
  const val ASSOCIATION_LOGO = "event_OrganiserImage"
  const val EVENT_LOCATION = "event_EventLocation"
  const val EVENT_DATE = "event_EventDate"
  const val EVENT_TIME = "event_EventTime"
  const val EVENT_CATCHY_DESCRIPTION = "event_EventCatchyDescription"
  const val EDIT_BUTTON = "event_EditButton"
}

object EventCreationTestTags {
  const val SCREEN = "eventCreationScreen"
  const val TITLE = "eventCreationTitle"
  const val EVENT_TITLE = "eventCreationEventTitle"
  const val SHORT_DESCRIPTION = "eventCreationShortDescription"
  const val COAUTHORS = "eventCreationCoauthors"
  const val TAGGED_ASSOCIATIONS = "eventCreationTaggedAssociations"
  const val DESCRIPTION = "eventCreationDescription"
  const val LOCATION = "eventCreationLocation"
  const val SAVE_BUTTON = "eventCreationSaveButton"
  const val EVENT_IMAGE = "eventCreationEventImage"
  const val START_TIME = "eventCreationStartTime"
  const val END_TIME = "eventCreationEndTime"
  const val ERROR_TEXT1 = "eventCreationStartAfterEnd"
  const val ERROR_TEXT2 = "eventCreationStartEqualsEnd"
  const val LOCATION_SUGGESTION_ITEM_LATITUDE = "eventCreationSuggestionItem: "
  const val START_DATE_FIELD = "eventCreationOverlayStartDateField"
  const val START_TIME_FIELD = "eventCreationOverlayStartTimeField"
  const val START_DATE_PICKER = "eventCreationOverlayStartDatePicker"
  const val START_TIME_PICKER = "eventCreationOverlayStartTimePicker"
  const val END_DATE_FIELD = "eventCreationOverlayEndDateField"
  const val END_TIME_FIELD = "eventCreationOverlayEndTimeField"
  const val END_DATE_PICKER = "eventCreationOverlayEndDatePicker"
  const val END_TIME_PICKER = "eventCreationOverlayEndTimePicker"
  const val TITLE_CHARACTER_COUNTER = "eventCreationNameCharacterCounter"
  const val SHORT_DESCRIPTION_CHARACTER_COUNTER = "eventCreationShortDescriptionCharacterCounter"
  const val DESCRIPTION_CHARACTER_COUNTER = "eventCreationDescriptionCharacterCounter"
}

object EventCreationOverlayTestTags {
  const val SCREEN = "eventCreationOverlayScreen"
  const val TITLE = "eventCreationOverlayTitle"
  const val BODY = "eventCreationOverlayBody"
  const val SEARCH_BAR_INPUT = "eventCreationOverlaySearchBarInput"
  const val CANCEL = "eventCreationOverlayCancel"
  const val SAVE = "eventCreationOverlaySave"
  const val ASSOCIATION_LIST = "eventCreationOverlayAssociationList"
}

object EventEditTestTags {
  const val SCREEN = "eventEditScreen"
  const val TITLE = "eventEditTitle"
  const val EVENT_TITLE = "eventEditEventTitle"
  const val SHORT_DESCRIPTION = "eventEditShortDescription"
  const val COAUTHORS = "eventEditCoauthors"
  const val TAGGED_ASSOCIATIONS = "eventEditTaggedAssociations"
  const val DESCRIPTION = "eventEditDescription"
  const val LOCATION = "eventEditLocation"
  const val LOCATION_SUGGESTION_ITEM = "eventCreationSuggestionItem: "
  const val SAVE_BUTTON = "eventEditSaveButton"
  const val DELETE_BUTTON = "eventEditDeleteButton"
  const val EVENT_IMAGE = "eventEditEventImage"
  const val START_TIME = "eventEditStartTime"
  const val END_TIME = "eventEditEndTime"
  const val ERROR_TEXT1 = "eventEditStartAfterEnd"
  const val ERROR_TEXT2 = "eventEditStartEqualsEnd"
  const val START_DATE_FIELD = "eventEditOverlayStartDateField"
  const val START_TIME_FIELD = "eventEditOverlayStartTimeField"
  const val START_DATE_PICKER = "eventEditOverlayStartDatePicker"
  const val START_TIME_PICKER = "eventEditOverlayStartTimePicker"
  const val END_DATE_FIELD = "eventEditOverlayEndDateField"
  const val END_TIME_FIELD = "eventEditOverlayEndTimeField"
  const val END_DATE_PICKER = "eventEditOverlayEndDatePicker"
  const val END_TIME_PICKER = "eventEditOverlayEndTimePicker"
}

object EventDetailsTestTags {
  const val SCREEN = "eventScreen"
  const val SNACKBAR_HOST = "snackbarHost"
  const val SNACKBAR_ACTION_BUTTON = "snackbarActionButton"
  const val GO_BACK_BUTTON = "goBackButton"
  const val SAVE_BUTTON = "eventSaveButton"
  const val SHARE_BUTTON = "eventShareButton"
  const val DETAILS_PAGE = "eventDetailsPage"
  const val DETAILS_IMAGE = "eventDetailsImage"
  const val DETAILS_INFORMATION_CARD = "eventDetailsInformationCard"
  const val TITLE = "eventTitle"
  const val ORGANIZING_ASSOCIATION = "eventOrganisingAssociation"
  const val ASSOCIATION_LOGO = "associationLogo"
  const val ASSOCIATION_NAME = "associationName"
  const val HOUR = "eventHour"
  const val START_DATE = "eventStartDate"
  const val END_DATE = "eventEndDate"
  const val DETAILS_BODY = "eventDetailsBody"
  const val PLACES_REMAINING_TEXT = "placesRemainingText"
  const val PRICE_TEXT = "priceText"
  const val DESCRIPTION = "eventDescription"
  const val LOCATION_ADDRESS = "eventLocation"
  const val MAP_BUTTON = "mapButton"
  const val SIGN_UP_BUTTON = "signUpButton"
  const val BOTTOM_SHEET = "eventBottomSheet"
  const val SEND_NOTIFICATION = "eventSendNotification"
}
